services:
  smppgc:
    image: "registry.smpp.be:5000/smpp/globalchat:${DEPLOY_VERSION}"
    restart: always
    environment:
      ROCKET_PROFILE: "beta"
    networks:
      - infra_db
      - infra_proxy
      - infra_metrics
    volumes:
      - gcproffilter-beta:/var/proffilter
    secrets:
      - oauth_google
    deploy:
      placement:
        constraints:
          - node.labels.db == true # This constraint can be lifted once we load proffilter data from db
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.smppgc-beta.rule=Host(`gcbeta.smartschoolplusplus.com`)"
        - "traefik.http.services.smppgc-beta.loadbalancer.server.port=8080"

volumes:
  gcproffilter-beta:

secrets:
  oauth_google:
    external: true

networks:
  infra_db:
    external: true
  infra_proxy:
    external: true
  infra_metrics:
    external: true
