[workspace]
resolver="2"
members= ["smppgc", "lmetrics", "string_tree", "profanity", "wordfilter", "ts_import", "nanotime"]

[workspace.package]
authors=["ldev <ldev@ldev.eu.org>"]
edition = "2021"
version = "2025.9.4"

[patch.crates-io]
rocket = { git="https://github.com/Xgames123/Rocket.git", branch="v0.5" }
rocket_ws = { git="https://github.com/Xgames123/Rocket.git", branch="v0.5" }
rocket_dyn_templates = { git="https://github.com/Xgames123/Rocket.git", branch="v0.5" }
rocket_db_pools = { git="https://github.com/Xgames123/Rocket.git", branch="v0.5" }

[profile.dev.package.sqlx-macros]
opt-level = 3
