services:
  smppgc:
    build:
      dockerfile: Dockerfile
      args:
        DEBUG: false
    networks:
      - ldeveuorg_backend_net
      - gc
    volumes:
      - proffilter:/var/proffilter

    expose:
      - 8080

volumes:
  proffilter:

networks:
  gc:
  ldeveuorg_backend_net:
    external: true
