services:
  smppgc:
    build:
      dockerfile: Dockerfile
      args:
        DEBUG: true
    networks:
      - ldeveuorg_backend_net
      - gc

    expose:
      - 8080

networks:
  gc:
  ldeveuorg_backend_net:
    external: true
