services:
  db:
    image: postgres
    user: postgres
    environment:
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_USER=smppgc
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - debugdb-data:/var/lib/postgresql/data
    networks:
      - gc

volumes:
  debugdb-data:
networks:
  gc:
