services:
  smppgc:
    image: "registry.smpp.be:5000/smpp/globalchat:${DEPLOY_VERSION}"
    restart: always
    networks:
      - infra_db
      - infra_proxy
      - infra_metrics
    volumes:
      - gcproffilter:/var/proffilter
    secrets:
      - oauth_google
    deploy:
      placement:
        constraints:
          - node.labels.db == true # This constraint can be lifted once we load proffilter data from db
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.smppgc-prod.rule=Host(`gc.smartschoolplusplus.com`)"
        - "traefik.http.services.smppgc-prod.loadbalancer.server.port=8080"



volumes:
  gcproffilter:

secrets:
  oauth_google:
    external: true

networks:
  infra_db:
    external: true
  infra_proxy:
    external: true
  infra_metrics:
    external: true
