export enum Packet {
  PACKET_MESSAGE = 0,
  PACKET_MESSAGE_PROF = 1,
  PACKET_MESSAGE_SYSTEM = 2,

  PACKET_SETUP = 3,
  PACKET_USERJOIN = 4,
  PACKET_MODJOIN = 5,
  PACKET_PROFANITY_WARN = 6,
  PACKET_MESSAGE_DEL = 7,
  PACKET_MESSAGE_CENSOR = 8,

}
export enum PacketC2S {
  PACKET_C2S_MESSAGE = 0,
  PACKET_C2S_DELMSG = 1,
  PACKET_C2S_BANMSGAUTHOR = 2,
}
