[package]
name = "smppgc"
version.workspace=true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-tungstenite={version="0.21.0"}
tokio={version="1.47.1", features=["macros", "rt-multi-thread", "sync"]}
futures-util={version="0.3.30"}
log={version="0.4.21"}
uuid={version="1.9.0", features=["v4", "serde"]}
thiserror={version="2.0.9"}
base64={version="0.22.1"}
dashmap={version="6.1.0"}
circular-queue={version="0.2.7"}
lmetrics={path="../lmetrics", features=["rocket"]}
wordfilter={path="../wordfilter", features=["serde"], default-features=false}
nanotime={path="../nanotime", features=["rocket"]}
lazy_static={version="1.5.0"}
serde_json={version="1.0.128"}
serde={version="1.0.219"}

reqwest={version="0.11.27", features=["json"]}
url={version="2.5.4"}
sqlx={version="0.7.4", features=["macros", "uuid", "tls-none"] }

rocket={version="0.5.1"}
rocket_ws={version="0.1.1"}
rocket_dyn_templates={version="0.2.0", features=["tera"]}
rocket_db_pools={version="0.2.0", features=["sqlx_postgres"]}

ts_import={path="../ts_import"}
rand = "0.9.2"
