[default]
address = "0.0.0.0"
port = 8080
ip_header="CF-Connecting-IP"

prof_filter_file="/var/proffilter/rules.txt"
static_dir="/app/www"
template_dir="/app/templates"

# chat
max_stored_messages=30
max_users=1000
max_ro_users=10

# user
max_username_len=30
max_claimed_names=2
max_name_retention=604800 # 7 days
max_session_age=2592000 # 30 days

[default.message_limits]
ratelimit="3/6"
max_len=300
min_len=2
small_len=150
large_penalty=2
max_spam=2

# [default.oauth.smartschool]
# redirect_uri="http://localhost/oauth/return"
# client_id="debug_client_id"
# client_secret_file="/debug_client_secret"

[default.oauth.google]
redirect_uri="http://localhost/oauth/return/google"
client_id="174379466053-6ob48jh8hfjdpmu726173d7iqabcdmcu.apps.googleusercontent.com"
client_secret_file="/run/secrets/oauth_secret_google"

[default.databases.sqlx]
url="postgres://postgres:smpppasswd@db/postgres"


############## DEBUG ##############
[debug]
debug=true
log_level="normal"

############## BETA ##############
[beta]
debug=false
log_level = "critical"

[beta.oauth.google]
redirect_uri="https://gcbeta.smartschoolplusplus.com/oauth/return/google"

[beta.databases.sqlx]
url="postgres://smpp:smpppasswd@db/smppbeta"


############## RELEASE ##############
[release]
debug=false
log_level = "critical"

[release.oauth.google]
redirect_uri="https://gc.smartschoolplusplus.com/oauth/return/google"

[release.databases.sqlx]
url="postgres://smpp:smpppasswd@db/smpp"
