[package]
name = "wordfilter"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
bincode={version="2.0.1", optional=true}
clap={ version = "4.5.4", features = ["derive"], optional = true }
unidecode = { version="0.3.0" }

[features]
default=["cli"]
bincode=["dep:bincode"]
cli=["dep:clap"]
